<?php

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../libs/autoload.php';


$configurator = new Nette\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$configurator->addConfig(__DIR__ . '/config/config.local.neon', $configurator::NONE); // none section
$container = $configurator->createContainer();

/**
 * Dumps information about a variable in Nette Debug Bar.
 * @param mixed $var variable to dump
 * @param string $title optional title
 * @param int $maxDepth maximum dumped depth of array and objects. Increasing this variable has huge impact on performance.
 * @param int $maxLength maximum length of strings
 */
function xcv($var, $title = '', $maxDepth = 3, $maxLength = 400)
{
	\Nette\Diagnostics\Debugger::$maxDepth = $maxDepth;
	\Nette\Diagnostics\Debugger::$maxLen = $maxLength;
	\Nette\Diagnostics\Debugger::barDump($var, $title);
}

return $container;
